[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
nanoid = "0.4.0"
chrono = "0.4.39"
skytable = "0.8.11"
dotenv = "0.15.0"
types = { path = "../types"}
serde = { version = "1.0.218", features = ["derive"] }
